package com.nfinity.fastcode.domain.model.Temp;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="s1", name="task")
public class Task {
	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="app_id", columnDefinition="int8")
	private Apps apps;

	@Basic
	@Column(length=2147483647)
	private String description;

	@Id
	@Column(columnDefinition="bigserial")
	private long id;

	@Basic
	@Column(length=2147483647)
	private String status;

	@Basic
	@Column(length=2147483647)
	private String type;


	public Task() {
	}

	public Task(long id) {
		this.id = id;
	}

	public Apps getApps() {
		return apps;
	}

	public void setApps(Apps apps) {
		this.apps = apps;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}